export const VEHICLE_OPTIONS = [
  "Voiture légère - Essence [L]",
  "Camion léger - Essence [L]",
  "Camion lourd - Essence [L]",
  "Motocyclette - Essence [L]",
  "Hors route 2 temps - Essence [L]",
  "Hors route 4 temps - Essence [L]",
  "Bateau - Essence [L]",
  "Bateau - Diesel [L]",
  "Bateau Cargo - Mazout [L]",
  "Voiture légère - Diesel [L]",
  "Camion léger - Diesel [L]",
  "Camion lourd - Diesel [L]",
  "Train - Diesel [L]",
  "Véhicule - Propane [L]",
  "Véhicule - Propane [kg]",
  "Véhicule - Propane [lbs]",
  "Véhicule - Électrique [kWh]",
  "Aviation - Kérosène [L]",
  "Aviation - Essence [L]",
]
